CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY, applied_at_utc TEXT NOT NULL);
CREATE TABLE experiments(experiment_id TEXT PRIMARY KEY);
CREATE TABLE tasks(task_id TEXT PRIMARY KEY);
CREATE TABLE configurations(configuration_id TEXT PRIMARY KEY);
CREATE TABLE runs(run_id TEXT PRIMARY KEY, experiment_id TEXT NOT NULL REFERENCES experiments(experiment_id), task_id TEXT NOT NULL REFERENCES tasks(task_id), configuration_id TEXT NOT NULL REFERENCES configurations(configuration_id));
CREATE TABLE run_states(id INTEGER PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), state TEXT NOT NULL, timestamp_utc TEXT NOT NULL);
CREATE TABLE event_sources(source TEXT PRIMARY KEY);
CREATE TABLE events(event_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), source TEXT NOT NULL REFERENCES event_sources(source), event_type TEXT NOT NULL, sequence INTEGER NOT NULL, source_sequence INTEGER NOT NULL, timestamp_utc TEXT NOT NULL, monotonic_ns INTEGER NOT NULL, measurement_class TEXT NOT NULL, payload_schema TEXT NOT NULL, payload_json TEXT, UNIQUE(run_id, sequence));
CREATE TABLE model_requests(id INTEGER PRIMARY KEY, event_id TEXT UNIQUE REFERENCES events(event_id), request_hash TEXT);
CREATE TABLE model_stream_events(id INTEGER PRIMARY KEY, event_id TEXT UNIQUE REFERENCES events(event_id), chunk_index INTEGER);
CREATE TABLE model_usage(id INTEGER PRIMARY KEY, event_id TEXT UNIQUE REFERENCES events(event_id), prompt_tokens INTEGER, completion_tokens INTEGER);
CREATE TABLE model_timings(id INTEGER PRIMARY KEY, event_id TEXT UNIQUE REFERENCES events(event_id), timing_name TEXT, original_value REAL, original_unit TEXT, normalized_value REAL);
CREATE TABLE agent_sessions(id INTEGER PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), session_id TEXT);
CREATE TABLE agent_turns(id INTEGER PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), turn_id TEXT);
CREATE TABLE tool_calls(id INTEGER PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), tool_call_id TEXT);
CREATE TABLE artifacts(id INTEGER PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), artifact_type TEXT, blob_digest TEXT);
CREATE TABLE artifact_blobs(digest TEXT PRIMARY KEY, algorithm TEXT NOT NULL, size_bytes INTEGER NOT NULL, relative_path TEXT NOT NULL);
CREATE TABLE validity_dimensions(id INTEGER PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), dimension TEXT NOT NULL, status TEXT NOT NULL, measurement_class TEXT NOT NULL, UNIQUE(run_id, dimension));
CREATE TABLE integrity_checks(id INTEGER PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), target TEXT NOT NULL, valid INTEGER NOT NULL, checked_at_utc TEXT NOT NULL);
CREATE TABLE normalization_runs(id INTEGER PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), normalizer_version TEXT NOT NULL, created_at_utc TEXT NOT NULL);
CREATE TABLE run_metrics(id INTEGER PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), metric_name TEXT NOT NULL, value REAL, unit TEXT, measurement_class TEXT NOT NULL, UNIQUE(run_id, metric_name));
